---
title: "Welcome to Data Science Resources for Change"
date: "Updated on: `r format(Sys.time(), '%d %B, %Y')`"
html_document:
    toc: no
---



$~$
$~$

# About This Site: A Note From Its Creators

$~$

Racism and bias exist everywhere, though it is not always obvious at first glance. 

This is particularly true in the field of data science. Due to their mathematical nature, data and algorithms are often treated as objective and unbiased when--in many cases--they are not. It can be easy to put trust in them; many people blindly support algorithms with little consideration of how they were created and how they operate in society. 

**In order to be thoughtful, effective, and inclusive data scientists, we believe it is important to understand the ways in which bias can play a dangerous role within our field, to understand the ways in which data can be used to either reinforce/exacerbate or fight oppression, and to support the inclusion of voices of color within the community.** 

Although these issues play a significant role in the discussion of data science in the media, very few classes at the undergraduate level cover them in detail. The few courses and projects we have been a part of that covered some of these topics have been fascinating and impactful to the way that we think about data science and our roles within the field. We wanted to create this site as a way to increase exposure to these ideas, spark constructive discussions, and help provide our fellow Smithies with knowledge and tools that can provide benefits long after graduation!

**This site is meant to serve as a resource for Smithies of all backgrounds who are interested in pursuing a future in statistical data sciences and want to learn more about these topics.** 

We have started a collection of different materials, from books and articles to videos, podcasts, and organizations to support, on the following topics revolving around data and race:

1) Algorithmic bias

2) Data in the criminal justice system

3) Diversity within the data science community


For those who are just beginning to dip their toes into these ideas, we hope that this site will provide a starting point to your educational journey, encouraging you to seek out further information and think about these ideas more in the future. For those who live these struggles every day, we hope that you can find something here you have not read or seen before, but also that you can find value through sharing these resources with others. 

As young, white students with next to no personal experience in this area, we do not want our voices to drown out those of others who may have valuable perspectives. We have attempted to promote content and organizations created by a diverse group of voices, but also acknowledge that our knowledge on the topic is limited. 

**We believe it is important for this educational process to be interactive and to include the voices of marginalized students within our community.** To promote this goal, we have create a content submission form where you can suggest additional resources that you think would be meaningful to share with your peers.

$~$

### Suggest a resource here!

https://forms.gle/w76mrUjqKtcojfCZA

$~$

**Additionally, we understand that our experiences may affect the way we choose to present information, perhaps resulting in an unbalanced perspective.** We will happily welcome your feedback on how to improve this site and ensure that the content shared here is authentic.

$~$

### Share feedback here!

https://forms.gle/TXNiin6KYNLSG7Rp9

$~$


-- *Audrey Bertin and Hannah Snell, '21*
[Creators of Data Science Resources for Change]


$~$

### _We hope you bookmark, share, and reference this site often._ 





